#!/usr/bin/env bash
# Bordo installer — run on your VPS:
#   curl -fsSL https://raw.githubusercontent.com/hasangenc0/bordo/master/install.sh | bash
# Or from a local clone:
#   ./install.sh

set -euo pipefail

BORDO_REPO="https://github.com/hasangenc0/bordo.git"
BORDO_DIR="${BORDO_DIR:-/opt/bordo}"

# ── colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${BLUE}▸${NC} $*"; }
success() { echo -e "${GREEN}✓${NC} $*"; }
warn()    { echo -e "${YELLOW}!${NC} $*"; }
die()     { echo -e "${RED}✗ ERROR:${NC} $*" >&2; exit 1; }
ask()     { echo -en "${BOLD}$*${NC}"; }  # prompt without newline

# ── banner ───────────────────────────────────────────────────────────────────
banner() {
  echo ""
  echo -e "${BLUE}${BOLD}  ╔══════════════════════════════════════╗${NC}"
  echo -e "${BLUE}${BOLD}  ║           B O R D O                  ║${NC}"
  echo -e "${BLUE}${BOLD}  ║   Open-source software factory        ║${NC}"
  echo -e "${BLUE}${BOLD}  ╚══════════════════════════════════════╝${NC}"
  echo ""
}

# ── os check ─────────────────────────────────────────────────────────────────
check_os() {
  [[ "$(uname)" == "Linux" ]] || die "This installer only supports Linux. On macOS, run: cd deploy/bordo && docker compose up --build"
  command -v apt-get &>/dev/null || command -v yum &>/dev/null || \
    die "Unsupported Linux distro. Tested on Ubuntu 22.04 / Debian 12 / RHEL 9."
}

# ── docker ───────────────────────────────────────────────────────────────────
install_docker() {
  if command -v docker &>/dev/null; then
    success "Docker $(docker --version | awk '{print $3}' | tr -d ,) already installed"
    return
  fi
  info "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    sudo usermod -aG docker "$USER"
    warn "Added $USER to the docker group — run 'newgrp docker' or re-login if compose fails"
  fi
  success "Docker installed"
}

# Resolve docker compose command (plugin or standalone)
compose_cmd() {
  if docker compose version &>/dev/null 2>&1; then
    echo "docker compose"
  elif command -v docker-compose &>/dev/null; then
    echo "docker-compose"
  else
    die "docker compose not found — install the Docker Compose plugin: https://docs.docker.com/compose/install/"
  fi
}

# ── repo ─────────────────────────────────────────────────────────────────────
setup_repo() {
  # If the script is running from inside a bordo clone, use that.
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd || echo "")"
  if [[ -f "${script_dir}/deploy/bordo/docker-compose.yml" ]]; then
    BORDO_DIR="$script_dir"
    success "Using existing repo at $BORDO_DIR"
    return
  fi

  if [[ -f "$BORDO_DIR/deploy/bordo/docker-compose.yml" ]]; then
    info "Updating existing install at $BORDO_DIR..."
    git -C "$BORDO_DIR" pull --ff-only || warn "git pull failed — continuing with current version"
  else
    info "Cloning Bordo to $BORDO_DIR..."
    git clone "$BORDO_REPO" "$BORDO_DIR"
  fi
  success "Repo ready at $BORDO_DIR"
}

# ── .env setup ───────────────────────────────────────────────────────────────
setup_env() {
  local compose_dir="$BORDO_DIR/deploy/bordo"
  local env_file="$compose_dir/.env"

  if [[ -f "$env_file" ]]; then
    # Already exists — just ensure BORDO_INTERNAL_TOKEN is present.
    if ! grep -q "^BORDO_INTERNAL_TOKEN=.\+" "$env_file" 2>/dev/null; then
      local tok
      tok=$(openssl rand -hex 32)
      echo "BORDO_INTERNAL_TOKEN=$tok" >> "$env_file"
      info "Generated BORDO_INTERNAL_TOKEN (internal service token)"
    fi
    success "Using existing .env at $env_file"
    export _BORDO_BASE_URL="$(grep '^BORDO_BASE_URL=' "$env_file" | cut -d= -f2- || echo '')"
    return
  fi

  # First install: write a minimal .env with only the internal service token.
  # All user-facing secrets are configured via 'bordo setup' after the server starts.
  local internal_token
  internal_token=$(openssl rand -hex 32)

  local default_ip
  default_ip=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "127.0.0.1")
  local base_url="http://$default_ip:7401"
  export _BORDO_BASE_URL="$base_url"

  cat > "$env_file" <<EOF
# Generated by Bordo installer — $(date -u +"%Y-%m-%d %H:%M UTC")
# All secrets (API keys, admin token) are configured via:
#
#   bordo setup --server $base_url
#
# Run that on your local machine after the services start.

# Internal service-to-service token (Docker network only — not the admin token).
BORDO_INTERNAL_TOKEN=$internal_token

# Ports
BORDOD_PORT=7401
AGENT_PORT=7402
CONSOLE_PORT=3000
EOF

  success ".env written (secrets will be set via 'bordo setup')"
}

# ── firewall ─────────────────────────────────────────────────────────────────
configure_firewall() {
  command -v ufw &>/dev/null || return
  local ufw_active
  ufw_active=$(sudo ufw status 2>/dev/null | head -1 || echo "inactive")
  [[ "$ufw_active" == *"active"* ]] || return

  info "Configuring UFW firewall..."
  sudo ufw allow 22/tcp   comment 'SSH'        &>/dev/null
  sudo ufw allow 3000/tcp comment 'Bordo console' &>/dev/null
  sudo ufw allow 7401/tcp comment 'Bordo API (CLI)' &>/dev/null
  # 7402 (agent) is intentionally not opened — accessed only via BFF
  success "Firewall: 22 (SSH), 3000 (console), 7401 (API) opened; 7402 (agent) blocked"
}

# ── start services ───────────────────────────────────────────────────────────
start_services() {
  local compose_dir="$BORDO_DIR/deploy/bordo"
  local cmd; cmd=$(compose_cmd)

  info "Building and starting Bordo services..."
  info "(First build takes ~5 minutes — grab a coffee)"
  echo ""

  $cmd -f "$compose_dir/docker-compose.yml" up -d --build

  echo ""
  info "Waiting for services to become healthy..."
  local retries=30
  while [[ $retries -gt 0 ]]; do
    local healthy
    healthy=$($cmd -f "$compose_dir/docker-compose.yml" ps --format json 2>/dev/null \
      | grep -c '"Health":"healthy"' 2>/dev/null || echo 0)
    [[ "$healthy" -ge 1 ]] && break
    sleep 4
    (( retries-- ))
  done
  success "Services started"
}

# ── summary ──────────────────────────────────────────────────────────────────
print_summary() {
  local server_ip
  server_ip=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")
  local base_url="${_BORDO_BASE_URL:-http://$server_ip:7401}"

  echo ""
  echo -e "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${GREEN}${BOLD}  Bordo is running!${NC}"
  echo -e "${GREEN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""
  echo -e "  Console  →  ${BLUE}http://$server_ip:3000${NC}"
  echo -e "  API      →  ${BLUE}$base_url${NC}"
  echo ""
  echo -e "${YELLOW}${BOLD}  Next: complete setup from your local machine${NC}"
  echo ""
  echo -e "  1. Install the Bordo CLI (no Go toolchain needed):"
  echo -e "     ${GREEN}curl -fsSL https://raw.githubusercontent.com/hasangenc0/bordo/master/install-cli.sh | sh${NC}"
  echo -e "     Or with Go: go install github.com/hasangenc0/bordo/cli/bordo@latest"
  echo ""
  echo -e "  2. Get the one-time setup token from the server logs:"
  echo -e "     ${GREEN}$(compose_cmd) -f $BORDO_DIR/deploy/bordo/docker-compose.yml logs bordod | grep setup_token${NC}"
  echo ""
  echo -e "  3. Run the setup wizard (enters API key, base URL, admin token):"
  echo -e "     ${GREEN}bordo setup --server $base_url${NC}"
  echo ""
  echo -e "  Logs:    $(compose_cmd) -f $BORDO_DIR/deploy/bordo/docker-compose.yml logs -f"
  echo -e "  Status:  $(compose_cmd) -f $BORDO_DIR/deploy/bordo/docker-compose.yml ps"
  echo -e "  Stop:    $(compose_cmd) -f $BORDO_DIR/deploy/bordo/docker-compose.yml down"
  echo ""
}

# ── main ─────────────────────────────────────────────────────────────────────
main() {
  banner
  check_os
  install_docker
  setup_repo
  setup_env
  configure_firewall
  start_services
  print_summary
}

main "$@"
