---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victoriametrics
  namespace: bordo-observe
  labels:
    app: victoriametrics
spec:
  serviceName: victoriametrics
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      containers:
        - name: victoriametrics
          image: victoriametrics/victoria-metrics:v1.103.0
          args:
            - -storageDataPath=/data
            - -retentionPeriod=30d
            - -httpListenAddr=:8428
          ports:
            - containerPort: 8428
              name: http
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: bordo-observe
spec:
  selector:
    app: victoriametrics
  ports:
    - name: http
      port: 8428
      targetPort: 8428
